[project]
name = "pico"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "ghulam.mustafa", email = "ghulam.mustafa@decimal.co.in" }
]
requires-python = ">=3.8.1"
dependencies = [
    "asyncpg>=0.30.0",
    "booktype>=1.5",
    "fastapi[standard]>=0.124.4",
    "langchain-community>=0.2.19",
    "langchain-core>=0.2.43",
    "langchain-ollama>=0.1.3",
    "langchain-openai>=0.1.25",
    "langchain-postgres>=0.0.10",
    "psycopg2>=2.9.10",
    "pydantic-settings>=2.8.1",
    "rank-bm25>=0.2.2",
    "redis>=4,<5",
    "sqlalchemy>=2.0.54",
    "structlog>=25.5.0",
]

[project.scripts]
pico = "pico:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
